### ISSUE TITLE
exception when checking file in project with wrong configuration

### ISSUE THREAD

**Issue by Bumshakalaka** [Bumshakalaka/SublimeLinter-contrib-nagelfar#6]
Scenario:
1. change a sublime project file by modifying path key to point to none exists folder e.g. "path": "/c/dupa",
2. Open such project in sublime
3. open some TCL file and lint the file

Observed:
SublimeLinter: Rebuilding in project folder: c:\dupa
SublimeLinter: Not initial scan - rebuild only one file 
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "Sublime Text 3\Data\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 111, in execute_lint_task
    errors = linter.lint(code, view_has_changed) or []
  File "Sublime Text 3\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 914, in lint
    cmd = self.get_cmd()
  File "Sublime Text 3\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 617, in get_cmd
    cmd = cmd()
  File "Sublime Text 3\Data\Packages\SublimeLinter-contrib-nagelfar\linter.py", line 333, in cmd
    databases = bd.rebuild(get_project_folder(), filename)
  File "Sublime Text 3\Data\Packages\SublimeLinter-contrib-nagelfar\linter.py", line 208, in rebuild
    persist.printf('Rebuild only one database for folder ' + folder)
TypeError: Can't convert 'bool' object to str implicitly

**Comment by level44** [comment]
Generation of database skipped for files outside project or with wrong project configuration
